DB_NAME="694remag"
DB_PASSWORD="xyzzy264"
DB_USER="root"
DB_HOST="localhost"
MAIL_USERNAME_INFO="singhjasdeep496@gmail.com"
MAIL_PASSWORD_INFO="xyzzy@&$88008010"
MAIL_DEFAULT_SENDER_INFO="singhjasdeep496@gmail.com"
